spring:
  datasource:
    url: jdbc:h2:mem:todo-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always

  logging:
    level:
      org.springframework.jdbc.core: DEBUG